services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8081:8081"
    depends_on:
      - db
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
volumes:
  pgdata: